fix: コンテンツの準備が出来ていないときにプレビューが404になる不具合
vivliostyle/vivliostyle-pub pull request #126
Opened 2021-11-15 06:33 UTC by AyumuTakai

#81 

コンテンツの準備が出来ていないときには空のHTMLファイルをvivliostyle viewerに渡すように変更しました。

将来的にはviewerのローディング表示に合わせるので暫定的な対応です。

2021-11-15 18:32 UTC, AyumuTakai commented
プレビュー対象でimgのsrcとCSSのurl()で指定されている画像が1MBより大きい場合にエラーをトーストで表示する機能を追加しました。

2021-11-16 14:35 UTC, takanakahiko requested changes
ありがとうございます！
少し気になった点があったの確認お願いします 🙏

2021-11-16 14:35 UTC, takanakahiko commented on web/src/components/MarkdownPreviewer.tsx
> +    setContentReady(false);
これってどのような意図がありますか？
なくても動くような気がしたので念の為確認です

2021-11-16 14:35 UTC, takanakahiko commented on web/src/components/MarkdownPreviewer.tsx
> +      setContentReady(true);
`iframeRef.current?.contentWindow?.location.reload()` がないとプレビューが更新されないと思いますがどうでしょうか？
`setContentReady(true);` のあとに入れる必要がありそうだなと思います

2021-11-16 14:35 UTC, takanakahiko commented on web/src/components/MarkdownPreviewer.tsx
> +  return <iframe ref={iframeRef} src={contentReady?viewerURL:VIVLIOSTYLE_VIEWER_HTML_URL+'#x=empty.html'} width="100%" height="100%"></iframe>;
`empty.html` は上部で const で定義しておきたいです

2021-11-16 14:49 UTC, AyumuTakai commented
contentReadyはリソースの準備が全て終ったら状態がfalseからtrueに変化してコンポーネントがリロードされ、viewerもリロードされます。
動作としてはほとんど iframeRef.current?.contentWindow?.location.reload() と同じですがReactっぽい記述になっていると思います。

contentReadyではなく、リソースの準備が終ったらempty.htmlから生成されたHTMLを含んだurlに変更する状態をフラグに使っても一石二鳥で良いかもしれません。

2021-11-16 15:31 UTC, AyumuTakai commented
すみません。うまく動かないですね。
今準備中の他の修正との関係で、正しく動いているものと勘違いしてしまいました。

一度取り下げます。

2021-11-16 15:31 UTC, closed without merging