fix/translation
vivliostyle/vivliostyle-pub pull request #156
Opened 2022-03-18 05:29 UTC by AyumuTakai

@MurakamiShinyu さんに監修頂いた翻訳辞書を更新しました。

また、i18nextを使った翻訳の抜け漏れを防ぐため、ソースコードからi18nextで指定したキーを抜き出してファイル(web/src/locales/extract_ja.json)に書き出し、既存の翻訳辞書(web/src/locales/ja/translation.json)と比較するスクリプトを追加しました。
[参考:key を自動で JSON ファイルに書き出す](https://suzukalight.com/blog/posts/2019-09-09-react-i18next#key-%E3%82%92%E8%87%AA%E5%8B%95%E3%81%A7-json-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%99)

2022-03-18 06:39 UTC, takanakahiko requested changes
PR ありがとうございます！何点か気になった部分を書いておいたので修正お願いします 🙏

2022-03-18 06:39 UTC, takanakahiko commented on web/package.json
> +    "//": "ソースコード中からt(...)を抽出してlocales/extract_ja.jsonに書き出す。その後、locals/ja/translation.jsonのキーリストと比較して足りないものを表示する",
これは README に書いて欲しいです

2022-03-18 06:39 UTC, takanakahiko commented on web/src/locales/checkkey.js
> +  //   console.log(key);
これは消しておいてもらえると嬉しいです

2022-03-18 06:39 UTC, takanakahiko commented on web/.gitignore
> +src/locales/extract_ja.json
最後に改行を入れといてください
https://odz.hatenablog.com/entry/20070112/1168618030

2022-03-18 06:59 UTC, AyumuTakai commented on web/src/locales/checkkey.js
> +  //   console.log(key);
チェック用のスクリプトは不要でしょうか?

このスクリプトが無いとbabel-plugin-i18next-extractパッケージで抽出したキーと、既存の翻訳辞書を目視で突き合せることになるのですが。

web/scriptsに移動するのはどうでしょうか。

2022-03-18 07:09 UTC, AyumuTakai commented on web/package.json
> +    "//": "ソースコード中からt(...)を抽出してlocales/extract_ja.jsonに書き出す。その後、locals/ja/translation.jsonのキーリストと比較して足りないものを表示する",
フロントエンド開発限定の細かいトピックに関してはweb/README.mdを作成してその中に記述し、
トップレベルのREADME.md にはweb/README.mdへの参照を記述するのはいかがでしょうか。

トップレベルのREADME.mdに細々と書くのもわかりにくくなるような気がしますので。

2022-03-18 08:20 UTC, takanakahiko commented on web/package.json
> +    "//": "ソースコード中からt(...)を抽出してlocales/extract_ja.jsonに書き出す。その後、locals/ja/translation.jsonのキーリストと比較して足りないものを表示する",
それでお願いします👍

2022-03-18 08:21 UTC, takanakahiko commented on web/src/locales/checkkey.js
> +  //   console.log(key);
コメントが不要ということです🙏

2022-03-18 23:48 UTC, takanakahiko commented on web/src/locales/checkkey.js
> +  //   console.log(key);
> web/scripts

こちらは賛成です！
開発者が実行するスクリプトと利用者に提供されるページを作っているソースコードは切り分けておきたいです。

2022-03-19 03:56 UTC, AyumuTakai commented on web/src/locales/checkkey.js
> +  //   console.log(key);
コメント削除&スクリプト移動しました。

2022-03-19 03:59 UTC, AyumuTakai commented on web/.gitignore
> +src/locales/extract_ja.json
私はeslint やエディタの設定に入れておかないと毎回忘れそうです。
Issue立ててコーディングルールをまとめたほうが良いかもしれませんね。

2022-03-19 04:00 UTC, AyumuTakai commented on web/package.json
> +    "//": "ソースコード中からt(...)を抽出してlocales/extract_ja.jsonに書き出す。その後、locals/ja/translation.jsonのキーリストと比較して足りないものを表示する",
ドキュメントを追加しました。

2022-03-19 06:46 UTC, takanakahiko commented on web/.gitignore
> +src/locales/extract_ja.json
POSIX の準拠についての話なので、この件に関してで言えば Issue たてることもないかなと思いました。
他にも共通認識揃えておきたければ必要かなとは思います。

2022-03-19 06:47 UTC, takanakahiko approved these changes
LGTM！

2022-03-19 06:47 UTC, merged